# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Bio',                url: 'bio'}
- {name: 'Libros',             url: 'books'}
- {name: 'Eventos',            url: 'events'}
- {name: 'Acompañamientos',    url: 'acompanamientos'}
- {name: 'Contacto',           url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'envelope', link:   'mailto:info@nataliatrigo.com'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: ''

related_posts: 'More stuff'

post_date_prefix: 'Written on'
